spring:
  application:
    name: todolist-be
  data:
    mongodb:
      host: localhost
      port: 27017
      database : todolist-db


wa :
  token : "Isi dengan token yang kamu dapatkan dari fonnte"
  url : "https://api.fonnte.com/send"